version: "3"

services:
  api:
    image: linkextractor-api:step6-python
    build: ./python-api
    ports:
      - "4567:4567"
    environment:
      - REDIS_URL=redis://redis:6379
      - USE_CACHE=false
    volumes:
      - ./logs:/app/logs
  web:
    image: linkextractor-web:step6-php
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:4567/api/
  redis:
    image: redis
