version: "3"

services:
  api:
    image: linkextractor-api:python
    build: ./python-api
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379
      - USE_CACHE=false
    volumes:
      - ./logs:/app/logs
  web:
    image: linkextractor-web:php
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
  redis:
    image: redis
